// Generated by `npx @convex-dev/auth`. Tells the deployment which JWT
// issuer to trust for incoming auth tokens.
//
// `CONVEX_SITE_URL` is a built-in env var auto-populated to the
// deployment's HTTPS host (e.g. https://glad-clam-537.convex.site).
// `npx convex env list` doesn't show it (only user-set vars), and
// `npx convex env set CONVEX_SITE_URL ...` is rejected as built-in,
// but it resolves correctly at runtime inside Convex functions.
//
// @convex-dev/auth signs JWTs with `iss = process.env.CONVEX_SITE_URL`
// at the same time, so verification has to match against the same value.
// Using SITE_URL here (the user's app URL) makes the issuer not match
// and surfaces as "No auth provider found matching the given token".
const authConfig = {
  providers: [
    {
      domain: process.env.CONVEX_SITE_URL,
      applicationID: "convex",
    },
  ],
};

export default authConfig;
