// Generated by `npx @convex-dev/auth`. Tells the deployment which JWT
// issuer to trust for incoming auth tokens. CONVEX_SITE_URL is the
// deployment's HTTP-actions host, set automatically by the Convex CLI.
const authConfig = {
  providers: [
    {
      domain: process.env.CONVEX_SITE_URL,
      applicationID: "convex",
    },
  ],
};

export default authConfig;
