// Generated by `npx @convex-dev/auth`. Tells the deployment which JWT
// issuer to trust for incoming auth tokens.
//
// The init script's auth.config.ts template referenced
// `process.env.CONVEX_SITE_URL`, but on this Convex version that env var
// is NOT auto-populated (and is reserved against manual override). The
// init script instead provisioned `SITE_URL` (set via `Step 1: Configure
// SITE_URL` during `npx @convex-dev/auth`), and @convex-dev/auth uses
// SITE_URL as the JWT issuer at signing time. So the verification-side
// `domain` here must also be SITE_URL for the issuer to match.
const authConfig = {
  providers: [
    {
      domain: process.env.SITE_URL,
      applicationID: "convex",
    },
  ],
};

export default authConfig;
